install.packages('doParallel', repos = 'http://cran.mirror.ac.za')
install.packages("tidyverse", repos = 'http://cran.mirror.ac.za')
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager", repos = 'http://cran.mirror.ac.za')
BiocManager::install("GENESIS", version = "3.8")