apiVersion: apps/v1
kind: Deployment
metadata:
  name: gveeden
  labels:
    app: gveeden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gveeden
  template:
    metadata:
      labels:
        app: gveeden
    spec:
      containers:
      - name: gveeden
        image: localhost:5000/gveeden/workspace
        command: ["/usr/sbin/sshd", "-D"]
        ports:
        - containerPort: 22
        volumeMounts:
        - mountPath: /root/gveeden/data
          name: sharedfs
        env:
        - name: COLUMNS
          value: "`tput cols`"
        - name: LINES
          value: "`tput lines`"
      volumes:
      - name: sharedfs
        flexVolume:
          driver: ceph.rook.io/rook
          fsType: ceph
          options:
            fsName: registryfs
            clusterNamespace: rook-ceph
            path: /gveeden
      nodeSelector:
        name: "n14"
