apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tina
  namespace: default
  labels:
    app: tina-ws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tina-ws
  template:
    metadata:
      labels:
        app: tina-ws
    spec:
      containers:
      - name: tina
        image: localhost:5000/tina/workspace
        command: ["/usr/sbin/sshd", "-D"]
        ports:
        - containerPort: 22
        volumeMounts:
        - mountPath: /root/tina/data
          name: user-storage
        env:
        - name: COLUMNS
          value: "`tput cols`"
        - name: LINES
          value: "`tput lines`"
      volumes:
      - name: user-storage
        flexVolume:
          driver: rook.io/rook
          fsType: ceph
          options:
            fsName: registryfs
            clusterNamespace: rook
            path: /tina
      nodeSelector:
        name: "n14"
